#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs hawk onto your system into ~/.local, making it available as ~/.local/bin/hawk.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export HAWK_CHANNEL=$(<crates/hawk/RELEASE_CHANNEL)
export HAWK_UPDATE_EXPLANATION="You need to fetch and rebuild hawk in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="hawk-linux-${arch}.tar.gz"
export HAWK_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
